name: Create GKE cluster with deployed Hazelcast Platform Operator

on:
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string
    secrets:
      project_id:
        required: true

jobs:
  create-cluster:
    name: Create GKE and deploy the operator
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: |-
        echo ${{ inputs.cluster_name }}
        echo ${{ secrets.project_id }}
    # Setup gcloud CLI
    # - uses: google-github-actions/setup-gcloud@v0.2.1
    #   with:
    #     service_account_key: ${{ secrets.GKE_SA_KEY }}
    #     project_id: ${{ env.PROJECT_ID }}
    #     export_default_credentials: true 

    # - name: Install Kubectl
    #   run: |-
    #     gcloud components install kubectl

    # - name: Create GKE cluster
    #   run: |-
    #     gcloud container clusters create "${{inputs.cluster_name}}" --zone="$GKE_ZONE" --project="${{ secrets.project_id }}" --machine-type=n1-standard-2 --num-nodes=2
    #     sleep 30

    # - name: Deploy Hazelcast Platform Operator
    #   run: |-
    #     kubectl apply -f https://repository.hazelcast.com/operator/bundle.yaml
    #     kubectl wait --for=condition=available --timeout=600s deployment/hazelcast-platform-controller-manager
