name: Create GKE cluster with deployed Hazelcast Platform Operator

on:
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string
    secrets:
      project_id:
        required: true

jobs:
  create-cluster:
    name: Create GKE and deploy the operator
    runs-on: ubuntu-latest

    steps:
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true 

    - name: Delete GKE cluster
      run: |-
        gcloud container clusters delete "${{inputs.cluster_name}}" --zone="$GKE_ZONE" --quiet
