name: Test on GKE
on:
  push:
    paths-ignore:
      - 'doc/**'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: europe-west1-b

jobs:
  create-gke-cluster:
    name: Create GKE cluster
    runs-on: ubuntu-latest
    outputs:
      cluster_name: ${{ steps.cluster.outputs.cluster_name }}

    steps:
      # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true 

    - name: Install Kubectl
      run: |-
        gcloud components install kubectl

    - name: Create GKE cluster
      id: cluster
      run: |-
        CLUSTER_NAME="operator-expose-externally-$GITHUB_RUN_NUMBER"
        echo "::set-output name=cluster_name::${CLUSTER_NAME}"
        gcloud container clusters create ${CLUSTER_NAME} --zone=${{ env.GKE_ZONE }} --project=${{ env.GCP_PROJECT_ID }} --network=${{ env.GCP_NETWORK }} --machine-type=n1-standard-2 --num-nodes=2
        sleep 30

  run-tests:
    name: Run Intergrational tests on GKE
    runs-on: ubuntu-latest
    needs: create-gke-cluster
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        include:
          - type: uisocket
            suffix: "-unisocket"
          - type: smart
            suffix: ""

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'
        cache: 'maven'
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17.2'

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true 

    - name: Install Kubectl
      run: |-
        gcloud components install kubectl

    - name: Connect to the GKE cluster
      run: gcloud container clusters get-credentials ${{ needs.create-gke-cluster.outputs.cluster_name }} --zone ${{ env.GKE_ZONE }} --project ${{ env.PROJECT_ID }}

    - name: Create namespace
      run: |-
        kubectl create namespace ${{ matrix.type }}

    - name: Deploy operator
      run: |-
        kubectl apply -n ${{ matrix.type }} -f https://repository.hazelcast.com/operator/bundle.yaml
        kubectl wait -n ${{ matrix.type }} --for=condition=available --timeout=600s deployment/hazelcast-platform-controller-manager

    - name: Deploy Hazelcast cluster
      run: |-
        kubectl create -n ${{ matrix.type }} secret generic hazelcast-license-key --from-literal license-key=${{ secrets.LICENSE }}
        kubectl apply -n ${{ matrix.type }} -f hazelcast${{matrix.suffix}}.yaml
        sleep 30
        kubectl wait -n ${{ matrix.type }} --for=condition=ready pod/my-hazelcast-0 --timeout=5m
        kubectl wait -n ${{ matrix.type }} --for=condition=ready pod/my-hazelcast-1 --timeout=150s
        kubectl wait -n ${{ matrix.type }} --for=condition=ready pod/my-hazelcast-2 --timeout=150s
        sleep 5

    - name: Wait for external IP to get assigned
      run: |-
        serviceType=$(kubectl get svc -n ${{ matrix.type }} my-hazelcast --output="jsonpath={.spec.type}")
        if [ "$serviceType" != "LoadBalancer" ]; then
          exit 1
        fi
        EXTERNAL_IP=$(kubectl get svc -n ${{ matrix.type }} my-hazelcast --output="jsonpath={.status.loadBalancer.ingress[0].ip}")
        while [ "$EXTERNAL_IP" == "" ]; do
          sleep 10
          EXTERNAL_IP=$(kubectl get svc -n ${{ matrix.type }} my-hazelcast --output="jsonpath={.status.loadBalancer.ingress[0].ip}")
        done

        echo "EXTERNAL_IP=${EXTERNAL_IP}" >> $GITHUB_ENV

    - name: Wait for Smart type member IPs to get assigned
      if: matrix.type == 'smart'
      run: |-
        for i in {0..2} do
          EXTERNAL_IP=$(kubectl get svc -n ${{ matrix.type }} my-hazelcast-${i} --output="jsonpath={.status.loadBalancer.ingress[0].ip}")
          while [ "$EXTERNAL_IP" == "" ]; do
            sleep 10
            EXTERNAL_IP=$(kubectl get svc -n ${{ matrix.type }} my-hazelcast-${i} --output="jsonpath={.status.loadBalancer.ingress[0].ip}")
          done
        done

    - name: Test Java Client
      run: |-
        EXTERNAL_IP="${{ env.EXTERNAL_IP }}"
        cd java${{matrix.suffix}}
        sed -i "s/<EXTERNAL-IP>/$EXTERNAL_IP/g" src/main/java/com/hazelcast/Main.java
        mvn package
        java -jar target/*jar-with-dependencies*.jar >> output-java.txt &
        PID=$!
        sleep 30
        kill $PID

        cat output-java.txt | grep 'Successful connection!' -q

    - name: Test Node.js Client
      run: |-
        EXTERNAL_IP="${{ env.EXTERNAL_IP }}"
        cd nodejs${{matrix.suffix}}
        sed -i "s/<EXTERNAL-IP>/$EXTERNAL_IP/g" client.js
        npm install
        npm start >> output-nodejs.txt &
        PID=$!
        sleep 30
        kill $PID

        cat output-nodejs.txt | grep 'Successful connection!' -q

    - name: Test Go Client
      run: |-
        EXTERNAL_IP="${{ env.EXTERNAL_IP }}"
        cd go${{matrix.suffix}}
        sed -i "s/<EXTERNAL-IP>/$EXTERNAL_IP/g" main.go
        go run main.go >> output-go.txt &
        PID=$!
        sleep 30
        kill $PID

        cat output-go.txt | grep 'Successful connection!' -q

    - name: Test Python Client
      run: |-
        EXTERNAL_IP="${{ env.EXTERNAL_IP }}"
        cd python${{matrix.suffix}}
        sed -i "s/<EXTERNAL-IP>/$EXTERNAL_IP/g" main.py
        pip install -r requirements.txt
        python main.py >> output-python.txt &
        PID=$!
        sleep 30
        kill $PID

        cat output-python.txt | grep 'Successful connection!' -q

    - name: Clean up
      if: ${{ always() }}
      run: |-
        kubectl delete ns ${{ matrix.type }}

  clean-up:
    name: Clean up GKE cluster
    runs-on: ubuntu-latest
    needs: [run-tests, create-gke-cluster]
    if: ${{ always() }}
    steps:

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true 

    # Clean up
    - name: Delete cluster
      run: |-
        gcloud container clusters delete "$clusterName" --zone="$GKE_ZONE" --quiet
